# Generated by Django 4.1.7 on 2023-03-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smqar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentracao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
